### ISSUE TITLE
Do not hardcode a default API key

### ISSUE THREAD

**Issue by s3rvac** [hugsy/binja-retdec#1]
Hi Hugsy. I am one of the developers behind RetDec. Thank you for your interest in our decompiler and use of the RetDec's API to create a plugin for Binary Ninja. We much appreciate this.

We would like to kindly ask you to remove the default API key from your source files and to generate a new one that will be used just by you. In the [API documentation](https://retdec.com/api/docs/essential_information.html), we ask the users to keep their API key a secret and not to disclose it to anyone. Each user has to use his or her own API key. Otherwise, we will be forced to block the account that caused the API key to leak.

**Comment by hugsy** [comment]
Hi @s3rvac 

First of all, thanks for RetDec, it is a great service.
As asked I have edited the code to prompt the user for an API key instead of defaulting to the one hardcoded. I had looked on https://retdec.com for a "Terms of Use" section, but couldn't find any, reason why I did it that way.

Hope that didn't make too much trouble for you.

Cheers.

**Comment by s3rvac** [comment]
Great, thanks!
