### ISSUE TITLE
Issues running on OSX

### ISSUE THREAD

**Issue by glem0** [hugsy/binja-retdec#2]
Cloning and running BN with pyenv set to system (2.7.X) does not populate right click menu with option to decompile.

Any suggestions?

**Comment by hugsy** [comment]
The plugin should work universally on all platform supported by BN. I would ask your question on BN GitHub or Slack.

**Comment by deepgray** [comment]
One animal is that the plugin is dropped in the same location as it does on Linux .binaryninja/plugins. On mac, there is a plugin directory in the users Library/Application Support/BinaryNinja/ directory... but if you move the directory binja-rent from .binaryninja to that it works. You just need to create a free account at AVGs site then use the API key to run the decompile.

**Comment by michael-myers** [comment]
All that needs to be done to close this issue is edit the README.md with a reminder that Binary Ninja stores its plugins at different paths.
- On a Mac: `~/Library/Application Support/Binary Ninja/plugins/`
- On Windows: `%APPDATA%\Binary Ninja\plugins` (I guess; haven't tested)
- ON Linux: `~/.binaryninja/plugins/`
