### ISSUE TITLE
MacOS variant stalls/hangs at "Integrating Binary Ninja Symbols...

### ISSUE THREAD

**Issue by deepgray** [hugsy/binja-retdec#5]
everything loads fine, but the status hangs with no progress...or logs to indicate any errors.

**Comment by hugsy** [comment]
I cannot help you since I don't have an OSX to test it on.

I would recommend to comment this line:
https://github.com/hugsy/binja-retdec/blob/master/retdec.py#L176

and see if it works.

**Comment by michael-myers** [comment]
I just tested on MacOS 10.12.3 and Binary Ninja 1.0.13, and was able to decompile a function without any issue. Doesn't seem to be a problem.

If @deepgray can share the binary that won't decompile, I can test whether I can confirm.

**Comment by deepgray** [comment]
[bomb.zip](https://github.com/hugsy/binja-retdec/files/796855/bomb.zip)

here's the CMU test program...i commented the suggested line out, and how it's hanging at "Decompilation done, preparing report"

**Comment by hugsy** [comment]
Must be an OSX issue or it is specific to you @deepgray. It's working very well on Linux
![](https://i.imgur.com/mw3UXbJ.png)

**Comment by michael-myers** [comment]
Decompilation works for me on MacOS. If the issue is specific to your setup, maybe it's a network issue between you and RetDec?

![screen shot 2017-02-23 at 2 56 08 pm](https://cloud.githubusercontent.com/assets/5177188/23276515/94e79ed4-f9d8-11e6-8e3b-9c82d963759d.png)

**Comment by cvediver** [comment]
@deepgray's issue occurs when selecting "Decompile *Binary* with RetDec," which is why @hugsy and @michael-myers were able to decompile *functions* without replicating this issue. `decompile_function()` calls `decompile_range_bytes()`, which sets `p["data"]["raw_entry_point"] = "{:#x}".format(self.session_data["address"])`. `decompile_file()` never sets `p["data"]["raw_entry_point"]`.

**Comment by deepgray** [comment]
haven't been back in a while...
